### ISSUE TITLE
图片大小的设置功能如何解决

### ISSUE THREAD

**Issue by dumbledorebryant** [tx19980520/Where-to-eat#5]

**Comment by dumbledorebryant** [comment]
要用到Python还是什么......

**Comment by tx19980520** [comment]
@dumbledorebryant css部分应该能解决，你去搜一下css缩放图片应该有很多可以解决的方案，如果实在是需要修图本身大小，就用我放在where_to_eat里面的py脚本去处理

**Comment by dumbledorebryant** [comment]
@tx19980520 好像可以直接设置width和height，有点暴力。。。
